services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - fight_base_network
    restart: on-failure

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - database
    networks:
      - fight_base_network
    env_file: ".env"
    environment:
      - POSTGRES_HOST=database
    restart: on-failure
    volumes:
      - .:/code

  database:
    image: postgres:latest
    container_name: fight_base_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: fight_base
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgressql/database
    networks:
      - fight_base_network


volumes:
  dbdata:
  postgres_data:

networks:
  fight_base_network:
